# Generated by Django 4.2.17 on 2024-12-26 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_alter_wallet_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.FloatField(verbose_name='Баланс кошелька'),
        ),
    ]
